/* SHORT VERSIONS of her exam-case model answers (26 Sep 2026). His words about the long answers: "very complex… very
   overwhelming… I don't know how anyone just like remembers that." So every written case question gets a short version:
   a few words a line, cut from the answer the bank carries (content/cases.js, or hs2-paper-m1's built cases for 2/3/4) —
   nothing added. Since 5 Oct 2026 every one of the 62 answers is HERS: the case 3 blood-pressure answer, the tool's until
   then (from her CVS 4 page), is now hers from her 29 May 2024 session (`swap` in cases.js). Her four recorded May 2024 case
   sessions supply the rest of 5 Oct's additions (case 13's progesterone question, all four of case 14, case 15's modes, case
   8's and case 9's unstarred yellow-case questions, case 9's synapse labels), with case 6's unstarred five from her deck. Lines
   that are the tool's say so in their src (case 14's last rods/cones line, the last levodopa line); two questions are worded by
   the tool around her material (case 3's lung micrographs, case 9's synapse labels). One mark per step; a line is one step, or one fact of a step that carries two.
     case  = the case id ('c2' = quiz case-c2) · k = the normalised opening of her question (must match exactly one)
     title = the trainer list's name for it · hook = one line to remember it by
     groups = the question's own parts; each line: [text, of] — of = the index of HER step the line is cut from.
   shorts.mjs gates it: every bold word is in the step it cites (normalised, whole words), every step of her answer has a
   line, 14 words a line at most, and every written case question has a short version. */
const G = (q, ...facts) => ({ q, facts: facts.map(([t, of]) => ({ t, of })) });

export const CASE_SHORTS = [
  /* ── Exam case 2 · The aftereffects of lymph node removal ──────────── */
  { case: 'c2', k: 'what are the major', title: 'Lymphatic system: three functions',
    hook: 'DIGEST fat, DEFEND the body, DRAIN the tissues.',
    groups: [
      G('Digestive', ['**Digestive**: **lacteals** in the gut absorb **dietary fat**', 0]),
      G('Immunological',
        ['**Immunological**: the **immune response**', 1],
        ['**thymus** (**T cells** mature), **bone marrow** (**B cells** mature)', 1],
        ['**lymph nodes**: where immune cells meet and coordinate', 1]),
      G('Fluid balance',
        ['**Fluid balance**: drains **excess tissue fluid**', 2],
        ['and returns it to the **venous system**', 2]),
    ] },
  { case: 'c2', k: 'what is the role', title: 'Axillary nodes and cancer spread',
    hook: 'Cancer escapes into the lymph; the SENTINEL node is checked first.',
    groups: [
      G('How cancer spreads',
        ['Spread of cancer = **metastasis**', 0],
        ['Cancer cells in the **lymphatic system** can reach **any part of the body**', 0]),
      G('Why the axillary nodes matter',
        ['The **axillary** (armpit) nodes are checked for **cancer cells**', 1],
        ['The first, closest to the breast, is the **sentinel node**', 1],
        ['Cancer there = it has **spread**; none = likely still in the breast', 1]),
    ] },
  { case: 'c2', k: 'why did mary develop', title: 'Mary\'s swollen arm',
    hook: 'Nodes out → drain BLOCKED → fluid stays → LYMPHOEDEMA.',
    groups: [
      G('Why the arm swells',
        ['Removing the **lymph nodes**: the arm\'s drainage is **blocked**', 0],
        ['Normally tissue fluid drains back at the **subclavian vein**', 1],
        ['Now the **lymphatic vessels** fill and cannot drain the tissue', 1],
        ['The swelling is **lymphoedema**', 1]),
    ] },

  /* ── Exam case 3 · Asthma ─────────────────────────────────────────── */
  { case: 'c3', k: 'what term is used', title: 'Difficulty breathing: the term',
    hook: 'DYS = bad, PNOEA = breathing.',
    groups: [G('The term', ['**Dyspnoea**: **dys** (bad) + **pnoea** (breathing)', 0])] },
  { case: 'c3', k: 'what is happening in', title: 'What asthma does to the airways',
    hook: 'SQUEEZE, SWELL, SLIME.',
    groups: [
      G('Three things narrow the airway',
        ['**Bronchoconstriction**: the airway **smooth muscle** has **contracted**', 0],
        ['**Inflammation**: the airway wall is thick with **swelling**', 1],
        ['More **mucus** secretion: less room for air', 2]),
    ] },
  { case: 'c3', k: 'how is ane s', title: 'Ane\'s ventilation and resistance',
    hook: 'Narrow pipes: HIGH resistance, HARDER work, EXTRA muscles.',
    groups: [
      G('Airway resistance',
        ['**Airway resistance** is **high** → **harder to breathe**', 0],
        ['It needs a **greater pressure difference** → **dyspnoea**', 0]),
      G('Ventilation',
        ['**Accessory respiratory muscles** are recruited', 1],
        ['An **increase in the work of breathing**', 1]),
    ] },
  { case: 'c3', k: 'how does an inhaler', title: 'How the reliever inhaler helps',
    hook: 'The reliever RELAXES the airway; the preventer calms inflammation.',
    groups: [
      G('The reliever',
        ['A reliever is a **bronchodilator**', 0],
        ['The airway **smooth muscle** is forced to **relax**, so the airway widens', 0],
        ['(A preventer is a **corticosteroid**: **anti-inflammatory**)', 0]),
    ] },
  { case: 'c3', k: 'how does the body', title: 'Keeping dust out of the lungs',
    hook: 'STICK and SWEEP, FILTER, COUGH.',
    groups: [
      G('The defences',
        ['**Mucus and cilia**: the **muco-ciliary escalator**', 0],
        ['**Nasal hairs** filter; particles stick in **mucus**', 1],
        ['The **carina** triggers the **cough reflex**', 2],
        ['The **epiglottis** keeps large objects out of the **trachea**', 2]),
    ] },
  { case: 'c3', k: 'the muco cillary escalator', title: 'The muco-ciliary escalator',
    hook: 'Mucus STICKS it, cilia SWEEP it up and out.',
    groups: [
      G('How it works',
        ['**Cilia** line the **respiratory epithelium**', 0],
        ['They **beat to sweep mucus up and out** of the airways', 0],
        ['**Mucus** is **sticky**: dust is **trapped** in it', 1]),
    ] },
  { case: 'c3', k: 'smoking damages this escalator', title: 'What smoking does to the escalator',
    hook: 'Cilia DAMAGED → mucus STUCK → smoker\'s COUGH.',
    groups: [
      G('The effect',
        ['The **cilia are damaged**', 0],
        ['so **mucus** cannot be moved **up and out**', 0],
        ['A **smoker’s cough** develops to replace them', 1]),
    ] },
  { case: 'c3', k: 'ane s blood pressure', title: 'Bringing Ane\'s blood pressure down',
    hook: 'STRETCH → MEDULLA: brake ON, accelerator OFF → vagus slows → vessels WIDEN.',
    groups: [
      G('Sense it',
        ['**Carotid** and **aortic baroreceptors** (**stretch receptors**) pick up **high** pressure', 0]),
      G('Tell the brain',
        ['To the **medulla oblongata**: **cardio-acceleratory**, **cardio-inhibitory**, **vasomotor** centres', 1]),
      G('Slow the heart',
        ['**Cardio-inhibitory** **stimulated**; **cardio-acceleratory** **inhibited**', 2],
        ['Via the **vagus nerve**: **rate** and **force** drop, **cardiac output** drops', 3]),
      G('Widen the vessels',
        ['**Vasomotor centre**: **vasodilation**, more **space** for the blood', 4]),
      G('Result',
        ['Blood pressure back down to **normal**', 5]),
    ] },
  { case: 'c3', k: 'her four lung micrographs', title: 'Four lung micrographs, A to D',
    hook: 'Cartilage stops at the bronchiole; muscle stops at the alveoli.',
    groups: [
      G('A · Trachea',
        ['**Trachea**: **ciliated pseudostratified columnar** epithelium', 0],
        ['**Cartilage** present; **smooth muscles** present', 1]),
      G('B · Bronchus',
        ['**Bronchus**: **ciliated pseudostratified columnar** epithelium (1)', 2],
        ['**Smooth muscles** (2) and **cartilage** (3) present', 3]),
      G('C · Bronchiole',
        ['**Bronchiole**: **cuboidal** epithelium', 4],
        ['Cartilage **absent**; **smooth muscles** present', 5]),
      G('D · Alveoli',
        ['**Type 1 pneumocytes**: **squamous** epithelium for **gaseous exchange**', 6],
        ['**Type 2** for **surfactant**; **macrophages** keep them clean', 7],
        ['**No cartilage** or **muscles**', 8]),
      G('The inhalers',
        ['**Bronchodilators** relax the muscle (**reliever**); **cortisol** daily (**preventer**)', 9]),
    ] },

  /* ── Exam case 4 · Panic attacks ──────────────────────────────────── */
  { case: 'c4', k: 'breathing or the process', title: 'Inhalation, step by step',
    hook: 'CONTRACT → BIGGER → LOWER pressure → air IN.',
    groups: [
      G('The steps',
        ['The **diaphragm contracts** (its dome lowers)', 0],
        ['The **external intercostal muscles contract**: ribs up and out', 0],
        ['The **thoracic cavity** enlarges; **intrapleural** pressure falls (**Boyle’s law**)', 1],
        ['**Intrapulmonary** volume increases, so its pressure falls', 2],
        ['Air flows in, **from high pressure to low**', 3]),
    ] },
  { case: 'c4', k: 'bullet point the steps', title: 'Exhalation, step by step',
    hook: 'RELAX → RECOIL → HIGHER pressure → air OUT.',
    groups: [
      G('The steps',
        ['The **diaphragm relaxes** (its dome rises)', 0],
        ['The **external intercostals relax**: ribs down and in', 0],
        ['The elastic lungs **recoil passively**', 1],
        ['**Intrapulmonary pressure rises** (**Boyle’s law**)', 2],
        ['Air flows out to the lower **atmospheric pressure**', 3]),
    ] },
  { case: 'c4', k: 'manaia feels tired after', title: 'The muscles of forced breathing',
    hook: 'IN: the neck lifts. OUT: the abs and internal intercostals squeeze.',
    groups: [
      G('Breathing in',
        ['At rest: **diaphragm** and **external intercostals** contract', 0],
        ['Forced: also **sternocleidomastoid** and **scalenes** (neck)', 0]),
      G('Breathing out',
        ['Forced: the **abdominal muscles** and **internal intercostals** contract', 1]),
    ] },
  { case: 'c4', k: 'what are some of', title: 'What makes ventilation harder',
    hook: 'BLOCKED airways, STIFF lungs, a LOST pleural seal.',
    groups: [
      G('Blocked airways',
        ['**Airway obstruction**: fluid, mucus, swelling (**COPD**, **asthma**)', 0],
        ['raises **resistance** and the muscular effort needed', 0]),
      G('Stiff lungs',
        ['Less **lung compliance**: **scar tissue**, rib cage or diaphragm problems', 1],
        ['No **surfactant**, or fluid in the **alveoli**', 1]),
      G('The pleural seal',
        ['Air in the pleural cavity (**pneumothorax**) collapses the lung (**atelectasis**)', 2]),
    ] },
  { case: 'c4', k: 'what is normal blood', title: 'Normal blood pH',
    hook: '7.35 to 7.45: below is acid, above is alkaline.',
    groups: [
      G('The range',
        ['**7.35–7.45** (average **7.4**)', 0],
        ['Below 7.35 = **acidotic**; above 7.45 = **alkalotic**', 0]),
    ] },
  { case: 'c4', k: 'draw the chemical equation', title: 'The bicarbonate buffer equation',
    hook: 'CO₂ + water ⇌ carbonic acid ⇌ H⁺ + bicarbonate.',
    groups: [
      G('The equation',
        ['**CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻**', 0],
        ['**carbon dioxide + water ⇌ carbonic acid ⇌ hydrogen ions + bicarbonate ions**', 0]),
    ] },
  { case: 'c4', k: 'how do changes in', title: 'Breathing rate and blood pH',
    hook: 'Blow off CO₂ → H⁺ FALLS → pH RISES: alkalosis.',
    groups: [
      G('The link',
        ['Rate and depth change the **CO₂** in the **alveoli** and the **blood**', 0],
        ['**Blood CO₂** drives the **bicarbonate buffer**', 1],
        ['so **H⁺** changes with it, and so does **pH**', 1]),
      G('Manaia',
        ['**Hyperventilation** blows off CO₂ → **H⁺ falls** → **pH rises**', 2],
        ['This is **respiratory alkalosis**', 2],
        ['(**Hypoventilation**: CO₂ up, H⁺ up → **respiratory acidosis**)', 2]),
    ] },
  { case: 'c4', k: 'how does the respiratory', title: 'How breathing corrects blood pH',
    hook: 'Too ACID → breathe FASTER. Too ALKALINE → breathe SLOWER.',
    groups: [
      G('Metabolic acidosis',
        ['**Metabolic acidosis** (**H⁺ up**): **hyperventilation**', 0],
        ['H⁺ becomes CO₂ and water; the extra **CO₂** is **breathed off**', 0]),
      G('Metabolic alkalosis',
        ['**Metabolic alkalosis** (**H⁺ down**): **hypoventilation**', 1],
        ['CO₂ is **kept** and turned back into H⁺ and bicarbonate', 1]),
    ] },

  /* ── Exam case 6 · Diabetes ───────────────────────────────────────── */
  { case: 'c6', k: 'where in the body', title: 'Where insulin is made',
    hook: 'Pancreas → islets → BETA cells make insulin (glucAgon = Alpha).',
    groups: [
      G('Where',
        ['The **endocrine pancreas**', 0],
        ['in the **islets of Langerhans**', 0]),
      G('Which cells',
        ['**Beta cells** make **insulin**, which **decreases blood sugar**', 1],
        ['(**Alpha cells** make **glucagon**)', 1]),
    ] },
  { case: 'c6', k: 'what hormone or hormones', title: 'Hormones that raise blood sugar',
    hook: 'GLUCAGON, the stress pair (ADRENALINE, CORTISOL), then GROWTH and THYROID.',
    groups: [
      G('The hormones and where they are made',
        ['**Glucagon**: the pancreas **alpha cells**', 0],
        ['**Adrenaline** (**adrenal medulla**) and **cortisol** (**adrenal cortex**)', 1],
        ['both mediate the **stress response**, which needs ready glucose', 1],
        ['**Growth hormone** (**anterior pituitary**) and **thyroid hormones**', 2]),
    ] },
  { case: 'c6', k: 'explain what insulin does', title: 'What insulin does at a cell',
    hook: 'TRAVEL, BIND, MOVE GLUT4, LET GLUCOSE IN.',
    groups: [
      G('The steps',
        ['Insulin travels in the **blood**', 0],
        ['It binds to **insulin receptors** on the cell surface', 1],
        ['A cascade moves **GLUT4** into the **cell membrane**', 2],
        ['GLUT4 lets **glucose** in, down its **concentration gradient**', 3],
        ['by **facilitated diffusion**', 3]),
    ] },
  { case: 'c6', k: 'insulin s role in the liver', title: 'Insulin in the liver',
    hook: 'Liver and muscle STORE glucose as GLYCOGEN.',
    groups: [G('Its role', ['**Glucose** → **glycogen**, by **glycogenesis**', 0])] },
  { case: 'c6', k: 'insulin s role in the muscles', title: 'Insulin in the muscles',
    hook: 'Same as the liver: glucose into GLYCOGEN.',
    groups: [G('Its role', ['**Glucose** → **glycogen**, by **glycogenesis**', 0])] },
  { case: 'c6', k: 'insulin s role in the fat', title: 'Insulin in fat tissue',
    hook: 'Fat tissue turns glucose into FAT: LIPOgenesis.',
    groups: [
      G('Its role',
        ['**Glucose** → **fats**, by **lipogenesis**', 0],
        ['the most **efficient storage form**', 0]),
    ] },
  /* the yellow case's unstarred questions (5 Oct 2026), her deck's answers */
  { case: 'c6', k: 'what other molecules also', title: 'What glucagon does to blood sugar',
    hook: 'Glucagon RAISES BGL three ways: glycogen, fat, new glucose.',
    groups: [
      G('Glucagon',
        ['**Glucagon**: breaks down **glycogen** (**glycogenolysis**)', 0],
        ['Breaks down **fats** (**lipolysis**)', 1],
        ['Liver: **gluconeogenesis**, **new glucose** from **non-glucose** sources', 2]),
    ] },
  { case: 'c6', k: 'insulin is designed to', title: 'Glucose and insulin over a day',
    hook: 'Spikes after MEALS; never zero; basal underneath, bolus on top.',
    groups: [
      G('Over the day',
        ['**BGL** follows your **meals** (**carbs** and **sugar**)', 0],
        ['**Background insulin**: insulin is **never at zero**', 1],
        ['BGL never zero either: stays in the **normal range**', 2],
        ['**Basal** = background; **bolus** = after **meals**', 3]),
    ] },
  { case: 'c6', k: 'in normal blood sugar', title: 'Does BGL leave the normal range?',
    hook: 'No.',
    groups: [G('The answer', ['**No**: it should not **exceed** the **normal range**', 0])] },
  { case: 'c6', k: 'what happens overnight what', title: 'Overnight and the morning',
    hook: 'Lowest at night; break the FAST in the morning.',
    groups: [
      G('Overnight',
        ['BGL is **lowest overnight**', 0],
        ['**Breakfast** = **breaking the fast**: hungry, **glycogen** run out', 1]),
    ] },
  { case: 'c6', k: 'when the body cells', title: 'When the pancreas tires',
    hook: 'Overworked pancreas → too little insulin → type 2 on insulin.',
    groups: [
      G('What happens',
        ['**Pancreatic fatigue**: **damage** from **overworking**', 0],
        ['**Low insulin**: **impaired** glucose regulation', 1],
        ['**Type 2** diabetes: may end up **on insulin**', 2]),
    ] },

  /* ── Exam case 8 · Joints and arthritis ───────────────────────────── */
  { case: 'c8', k: 'arthritis is a condition', title: 'The joint, A to H',
    hook: 'Muscle, enthesis, fluid, bursa, capsule, tendon, bone, cartilage, ligament.',
    groups: [
      G('Each letter: structure and function',
        ['A: **muscle**, **contracts** to move the bones', 0],
        ['A (the other two): **enthesis**, where the **ligaments attach**', 1],
        ['B: **synovial fluid**, **lubricates** the joint', 2],
        ['C: **bursa**, **reduces friction**', 3],
        ['D: **joint capsule**, **holds the bones together**', 4],
        ['E: **tendon**, **joins muscle to bone**', 5],
        ['F: **bone**, a **lever** that **articulates** at joints', 6],
        ['G: **hyaline cartilage**, **reduces friction** and **absorbs shock**', 7],
        ['H: **ligament**, **holds bones together**', 8]),
    ] },
  { case: 'c8', k: 'what occurs in rheumatoid', title: 'Rheumatoid arthritis',
    hook: 'AUTOIMMUNE, FAST, BOTH SIDES, WHOLE BODY.',
    groups: [
      G('What occurs',
        ['**Autoimmune**: the **immune system attacks the joints**', 0],
        ['Onset is **relatively rapid**, over **weeks to months**, at any age', 1],
        ['Joints **painful, swollen and stiff**, on **both sides** of the body', 2],
        ['**Morning stiffness** longer than **1 hour**', 2],
        ['**Whole-body** symptoms: **fatigue**, feeling ill', 3]),
    ] },
  { case: 'c8', k: 'what is the other', title: 'The other arthritis',
    hook: 'OSTEO-arthritis: the wear-and-tear one.',
    groups: [G('Its name', ['**Osteoarthritis**', 0])] },
  { case: 'c8', k: 'what is the difference', title: 'Osteoarthritis vs rheumatoid',
    hook: 'Cause, onset, joints, whole body: rheumatoid is immune, fast, both sides, systemic.',
    groups: [
      G('Cause', ['Rheumatoid: **autoimmune**; osteo: **wear and tear**', 0]),
      G('Onset', ['Rheumatoid: any age, **weeks to months**; osteo: **later in life**, **over years**', 1]),
      G('Joints',
        ['Rheumatoid: **swollen**, **symmetrical**, stiffness **over 1 hour**', 2],
        ['Osteo: **ache**, little swelling, **one set of joints**, **under 1 hour**', 2]),
      G('Whole body', ['Rheumatoid has **whole body symptoms**; osteo does not', 3]),
    ] },
  { case: 'c8', k: 'where is cortisol produced', title: 'Where cortisol comes from',
    hook: 'Adrenal CORTEX, on the kidney, told by ACTH.',
    groups: [
      G('Where',
        ['The **adrenal glands**, on top of the **kidneys**', 0],
        ['in the **adrenal cortex** (the outer part)', 1]),
      G('What releases it', ['**ACTH** from the **anterior pituitary**', 1]),
    ] },
  { case: 'c8', k: 'what are the functions', title: 'Cortisol and the stress response',
    hook: 'More SUGAR, steady BLOOD VOLUME, LESS inflammation.',
    groups: [
      G('What it does',
        ['**Increases blood glucose** by **gluconeogenesis**', 0],
        ['and raises blood **fatty acids** and **amino acids**', 0],
        ['Reduces **inflammation** and **suppresses the immune system**', 3]),
      G('How that helps with stress',
        ['Helps resist **chronic** (long-term) **stress**: steady **blood sugar**', 1],
        ['Keeps up **blood volume**, so **tissue perfusion** continues', 2]),
    ] },
  { case: 'c8', k: 'how is cortisol going', title: 'Cortisol for Shannon\'s arthritis',
    hook: 'Calms the SWELLING, calms the IMMUNE attack.',
    groups: [
      G('How it helps',
        ['**Reduces inflammation**: less **swelling**, **redness** and **pain**', 0],
        ['**Suppresses the immune system**: RA is **autoimmune**', 1]),
    ] },
  /* the yellow case's unstarred questions (5 Oct 2026) */
  { case: 'c8', k: 'the knee and hip', title: 'Why synovial joints matter',
    hook: 'FREELY movable: without them, very little movement.',
    groups: [
      G('Benefits',
        ['Synovial joints are **freely movable**', 0],
        ['The **most freely moving** joints: without them, **very limited movement**', 1]),
    ] },
  { case: 'c8', k: 'what kind of synovial', title: 'Hip, knee, shoulder, elbow: joint types',
    hook: 'Ball-and-socket: shoulder, HIP. Hinge, like a door: KNEE, elbow.',
    groups: [
      G('Types',
        ['**Shoulder** and **hip**: **ball-and-socket**', 0],
        ['**Knee** and **elbow**: **hinge**, open and close like a **door**', 1]),
    ] },
  { case: 'c8', k: 'what is bursitis', title: 'Bursitis',
    hook: 'A friction CUSHION that gets inflamed.',
    groups: [
      G('The bursa',
        ['**Bursa**: a **fluid-filled** **sac** between bone and soft tissue', 0],
        ['A **cushion** to reduce **friction**', 0]),
      G('Bursitis',
        ['**Inflamed** and **swollen**: the **opposite effect**, and painful', 1]),
    ] },
  { case: 'c8', k: 'what might you say', title: 'What to tell Shannon',
    hook: 'RA is autoimmune: ANY age.',
    groups: [
      G('What to say',
        ['**Rheumatoid arthritis** is **autoimmune**: it can hit at **any age**', 0],
        ['Not the **wear and tear** of osteoarthritis, which begins **later in life**', 1]),
    ] },

  /* ── Exam case 9 · Neurotransmitters and the brain ───────────────── */
  { case: 'c9', k: 'what is a neurotransmitter', title: 'Neurotransmitters and dopamine',
    hook: 'A chemical across the synapse; dopamine from the SUBSTANTIA NIGRA.',
    groups: [
      G('What a neurotransmitter is',
        ['A **chemical** released at the **presynaptic** endings of a **chemical synapse**', 0],
        ['It acts on the **receptor** region of the **postsynaptic neuron**', 0]),
      G('Where dopamine is made',
        ['**Dopamine**: the **substantia nigra** of the **midbrain**', 1]),
    ] },
  { case: 'c9', k: 'explain the role of', title: 'Calcium at the synapse',
    hook: 'Impulse ARRIVES → Ca²⁺ IN → vesicles RELEASE.',
    groups: [
      G('Calcium\'s role',
        ['The **action potential** reaches the **axon terminal**', 0],
        ['**Ca2+ channels open**; Ca2+ enters the **presynaptic neuron**', 0],
        ['Ca2+ opens the **vesicles**: neurotransmitter out by **exocytosis**', 1]),
    ] },
  { case: 'c9', k: 'explain the process of', title: 'Synaptic transmission',
    hook: 'ARRIVE, CALCIUM, RELEASE, CROSS, BIND, RESPOND, CLEAR.',
    groups: [
      G('The steps',
        ['The **action potential** reaches the **axon terminal**', 0],
        ['**Ca2+** enters the **presynaptic neuron**', 0],
        ['Vesicles release it into the **synaptic cleft** (**exocytosis**)', 1],
        ['It **diffuses across the synaptic cleft**', 2],
        ['It **binds to receptors** on the **postsynaptic neuron**', 3],
        ['**Permeability** changes: **excitatory** or **inhibitory**', 4],
        ['Then **re-uptake** or **enzymatic destruction**', 5]),
    ] },
  { case: 'c9', k: 'when neurotransmitters bind to', title: 'When a neurotransmitter binds',
    hook: 'The gate changes: EXCITE or INHIBIT.',
    groups: [
      G('What happens',
        ['The **postsynaptic membrane’s permeability changes**', 0],
        ['**Excitatory** or **inhibitory**: **stimulated or inhibited**', 1]),
    ] },
  { case: 'c9', k: 'after the neurotransmitter has', title: 'Clearing the signal',
    hook: 'Take it BACK or BREAK it down.',
    groups: [
      G('What happens to it',
        ['**Re-uptake** into the **presynaptic neuron**', 0],
        ['or **enzymatic destruction**', 0]),
    ] },
  { case: 'c9', k: 'label her synapse figure', title: 'Label the synapse, A to G',
    hook: 'VESICLES mean pre (F); RECEPTORS mean post (G).',
    groups: [
      G('The letters',
        ['**A**: **calcium channel**', 0],
        ['**B**: **vesicle**', 1],
        ['**C**: **neurotransmitter** molecules', 2],
        ['**D**: **reuptake** channel', 3],
        ['**E**: **receptors**', 4],
        ['**F**: **presynaptic** neuron (the **vesicles**)', 5],
        ['**G**: **postsynaptic** neuron (the **receptors**)', 6]),
      G('The processes',
        ['**Exocytosis**: the **vesicle fuses**, releasing the neurotransmitter', 7],
        ['**Diffusion** across the **synaptic cleft**', 8]),
    ] },
  { case: 'c9', k: 'levodopa which travels through', title: 'Why levodopa, not dopamine',
    hook: 'Only what crosses the BLOOD-BRAIN BARRIER works on the brain.',
    groups: [
      G('Why',
        ['Must cross the **blood-brain barrier** to work on brain cells', 0],
        ['Not **fat soluble**: cannot cross, **useless** for the brain', 1],
        ['**Levodopa** crosses, becomes **dopamine**; dopamine itself **does not cross**', 2]),
    ] },

  /* ── Exam case 10 · Stroke and the brain ──────────────────────────── */
  { case: 'c10', k: 'review the functional regions', title: 'Cerebrum areas, A to G',
    hook: 'A to G: PLAN, SPEAK, MOVE, FEEL, HEAR, UNDERSTAND, SEE.',
    groups: [
      G('Each letter',
        ['A: **prefrontal cortex**', 0],
        ['B: **Broca’s area**', 1],
        ['C: **motor area**, **precentral gyrus**', 2],
        ['D: **somatosensory area**, **postcentral gyrus**', 3],
        ['E: **auditory area**', 4],
        ['F: **Wernicke’s area**', 5],
        ['G: **occipital** (**visual**) area', 6]),
    ] },
  { case: 'c10', k: 'for each region brainstorm', title: 'What damage to each area does',
    hook: 'Lose what it does: judgement, speech, movement, touch, hearing, understanding, sight.',
    groups: [
      G('Each area, damaged',
        ['A prefrontal: **poor judgement**, **inappropriate behaviour**, **loss of focus**', 0],
        ['B Broca’s: **difficulty producing speech** and writing', 1],
        ['C motor: **loss of voluntary movement**', 2],
        ['D somatosensory: **loss of touch** and general sensation', 3],
        ['E auditory: **hearing affected**', 4],
        ['F Wernicke’s: **cannot understand language**', 5],
        ['G occipital: **vision affected**', 6]),
    ] },

  /* ── Exam case 13 · Fertility ─────────────────────────────────────── */
  { case: 'c13', k: 'what is an ovulation', title: 'The ovulation predictor kit',
    hook: 'It catches the LH PEAK in urine.',
    groups: [
      G('What it shows',
        ['When **ovulation** is about to happen', 0],
        ['It picks up the **peak** in **luteinizing hormone** (**LH**) in the **urine**', 0]),
    ] },
  { case: 'c13', k: 'what occurs during ovulation', title: 'What happens at ovulation',
    hook: 'LH PEAK → follicle BURSTS → oocyte OUT → toward the FIMBRIAE.',
    groups: [
      G('What occurs',
        ['A **secondary oocyte** is released from the **ovary**', 0],
        ['Triggered by a **peak** in **LH**', 1],
        ['The **Graafian** (tertiary) **follicle** bursts; the ovarian wall **ruptures**', 2],
        ['Fluid pushes the oocyte to the **fimbriae** of the **Fallopian tube**', 3]),
    ] },
  { case: 'c13', k: 'what days of a', title: 'The fertile days',
    hook: 'Days 10 to 17.',
    groups: [G('The days', ['**Days 10–17**', 0])] },
  { case: 'c13', k: 'can you explain why', title: 'Why the hormones change',
    hook: 'Each hormone has a job: FSH grows, estrogen thickens, LH releases, progesterone prepares.',
    groups: [
      G('Why',
        ['Each hormone drives a **different process**', 0],
        ['**Follicles** develop (**FSH**); the **uterine lining** thickens (**estrogen**)', 1],
        ['**Ovulation** (**LH**); ready for **implantation** (**progesterone**)', 1]),
    ] },
  { case: 'c13', k: 'how would pregnancy change', title: 'Pregnancy and the hormone graph',
    hook: 'No DROP at day 21: the levels keep RISING.',
    groups: [
      G('The change',
        ['The **hormone drop** at about **day 21** does not happen', 0],
        ['**Estrogen** and **progesterone** keep **rising**', 1]),
    ] },
  { case: 'c13', k: 'hormonal methods of contraception', title: 'How progesterone contraception works',
    hook: 'STOP ovulation, BLOCK the sperm, FAKE a pregnancy.',
    groups: [
      G('What progesterone does',
        ['Prevents **ovulation**: stops the **LH** being released', 0],
        ['Thickens the **cervical mucus**: keeps the **sperm** out', 1],
        ['Imitates **pregnancy**: keeps **progesterone** levels **high**', 2]),
    ] },

  /* ── Exam case 14 · RG colour blindness (her 2024 session + her 413286 post) ── */
  { case: 'c14', k: 'what is red green colour', title: 'Rods, cones and RG colour blindness',
    hook: 'Cones see COLOUR; RG = faulty L (red) and M (green) cones.',
    groups: [
      G('Cones and rods',
        ['**Cones**: **colour**, **central** vision, in **good light**, more **detailed**', 0],
        ['**Rods**: **grey scale**, more **sensitive** to light, work in **dim light**', 1],
        ['**Macula**: cones and rods; **fovea**: **only cones**', 2]),
      G('What RG colour blindness is',
        ['A **genetic defect** (an anomaly) of the **cones** of the **retina**', 3],
        ['Faulty **L cones** (**red**, long wavelength) and **M cones** (**green**, medium)', 4],
        ['Detected with a **colour-blindness test**', 5]),
      G('In the question’s words',
        ['Cones = **photopic**, colour, central; rods = **scotopic**, **peripheral**', 6]),
    ] },
  { case: 'c14', k: 'draw a pedigree chart', title: 'Every relative’s genotype',
    hook: 'Grandad’s Xb → carrier MUM → Simon XbY; his dad gives only a Y.',
    groups: [
      G('Mum’s side',
        ['**Grandfather**: **XbY** (a colour-blind man)', 0],
        ['**Grandmother**: **XBXb**, a **carrier** (she has a colour-blind daughter)', 1],
        ['**Aunt**: **XbXb** (the defect on **both** X chromosomes)', 2],
        ['**Uncle**: **XBY** (not colour-blind)', 5]),
      G('Simon’s family',
        ['**Mum**: **XBXb**, a **carrier**; her **XB** gives **normal vision**', 3],
        ['**Dad**: **XBY**, he has the **normal X**', 4],
        ['**Simon**: **XbY**; Xb from his **mum**, only a **Y** from dad', 6]),
    ] },
  { case: 'c14', k: 'given the above and', title: 'How RG colour blindness is inherited',
    hook: 'X-linked RECESSIVE: carrier mums, affected sons; dads never to sons.',
    groups: [
      G('The pattern',
        ['**X-linked recessive**: the **L** and **M** cone genes are on the **X**', 0],
        ['Carried by **mothers**, shows in **50%** of their **sons**', 1],
        ['Shows only when **all X** chromosomes are affected: a woman needs **both**', 2],
        ['Can **skip a generation**', 5]),
      G('Fathers',
        ['**Never** to their **sons**: sons get only a **Y**', 3],
        ['**Always** the affected X to **all** their **daughters**', 4]),
    ] },
  { case: 'c14', k: 'will simon pass on', title: 'Will Simon pass it on?',
    hook: 'Sons get his Y (clear); daughters get his Xb (carriers).',
    groups: [
      G('His children',
        ['**None** of his **sons**: they get his **Y**', 0],
        ['**All** his **daughters**, as **unaffected carriers**: they get his **X**', 1]),
    ] },

  /* ── Exam case 15 · Genetic diseases (her 2024 session) ──────────────── */
  { case: 'c15', k: 'what are the modes', title: 'CF and Huntington’s: modes of inheritance',
    hook: 'CF: autosomal RECESSIVE, rr, skips generations. HD: autosomal DOMINANT, every generation.',
    groups: [
      G('Cystic fibrosis',
        ['**Autosomal recessive**, on **chromosome 7**', 0],
        ['**Skips generations**; people can be **carriers**', 1],
        ['Affected person: **rr**', 2]),
      G('Huntington’s disease',
        ['**Autosomal dominant**, on **chromosome 4**', 3],
        ['Shows whenever the **dominant allele** is present: **every generation**', 4],
        ['Affected person: **Rr** or **RR**', 5]),
    ] },
];
