/* The TEN STARRED CASES the HS2 final is built on — her words: the exam "will be based on the starred *Case studies in your
   Case Study Booklet A" (Assessment Overview), 130 min, 32 questions, 37% short answer.
   Scenarios and questions are HERS, verbatim from "Case Study Workbook 2026 S2" (only the starred questions are listed).
   Answers are HERS wherever she has posted one: each `steps` list = her answer split one marking point per line (spelling
   tidied, nothing added), and `src` names the deck and slide. Where a line is the tool's reading, `src` says so.
   Cases 2, 3 and 4 are NOT repeated here: `from:'m1:<id>'` imports them from hs2-paper-m1's built bank, where they were
   written from the same deck on 2026-09-06.
   `held` = a starred question she has not answered anywhere we can read yet (her answer is hidden on Canvas, or her quiz
   only covers part of the case). It is listed on the case's checklist row so nothing starred goes missing, but it is never
   dealt as a written question without a model answer.
   `formative` = normalised stem fragments of the CASE STUDY FORMATIVE TEST MODULE 1-2 (211092) questions that belong to
   this case; `pull` = module checklist rows (or a whole quiz, 'm3:211050') whose questions the case's row also deals —
   named here, never guessed by keyword.
   `done / ask / cap` are the tool's reading of her questions (21 Sep 2026). */
const DECK24 = 'Her answer · 2024 case-study model-answers deck (Lym Panic Asth Diab)';
const JOINTS = 'Her answer · 2024 case-study model-answers deck (joints, inflammation)';
const NS24 = 'Her answer · 2024 NS case-study answers deck';
const FERT = 'Her answer · her MODULE 3 CASES: FERTILITY QUIZ (211050), which her Anatomy Mondays 15 page names as this case’s model answer';
/* Her 31 May 2024 case-study session, transcribed locally 5 Oct 2026 (the video stays off this repo): she talks through her
   Fertility quiz, then her RG colour-blindness quiz (the one still hidden on Canvas as 211016) and keys it 10/10 on screen,
   then marks the genetic-diseases board. Times are into that video. */
const S24 = 'Her answer · her 31 May 2024 case-study session (Canvas page “RECORDINGS EXAM PREP & CASE STUDIES Model answers”, the Fertility & Red green colorblindness video)';

export const CASES = [
  { id: 'c2', n: 2, from: 'm1:lymph', mod: 'm1', sys: 'lymph', name: 'Exam case 2 · The aftereffects of lymph node removal',
    formative: ['role of the axillary lymph nodes in the spread of cancer'],
    done: 'Say what the lymphatic system does (three jobs), how cancer reaches the axillary nodes and why they are checked, and why removing them swells the arm (lymphoedema — the drainage route is gone).',
    ask: 'Short written answers of 2–3 marks each; her formative test turns the metastasis question into drop-downs.',
    cap: 'Functions, metastasis via the sentinel node, and the fluid-drainage reason for the swelling.' },
  { id: 'c3', n: 3, from: 'm1:asthma', mod: 'm1', sys: 'resp', name: 'Exam case 3 · Asthma',
    /* `more` (5 Oct 2026): her workbook's "Images of different parts of the lungs" — four micrographs in a table she fills in
       herself — is not a starred question, but her EXAM CASE STUDY HELPLINE links "CASE STUDY LUNG HISTOLOGY FOR EXAM" under
       this case and she says the exam's diagrams and graphs are the booklet's. The question wording and the A–D letters are the
       tool's; every answer line is hers (the workbook table, and her deck's slide 2 for the reliever and preventer). */
    more: [
      { q: 'Her four lung micrographs, A to D (Case Study Workbook, case 3, “Images of different parts of the lungs”): name the part of the airway each one shows, and give its lining and whether cartilage and smooth muscle are present.', marks: 10, img: 'wb26-lung4.png',
        src: 'Her answer · her Case Study Workbook 2026 S2, case 3 (the answers are in her own table under the four images), and her CASE STUDY LUNG HISTOLOGY FOR EXAM deck, slide 2, for the last line. The question wording and the A–D letters are the tool’s: the table is not starred, but her exam helpline links that deck under this case',
        steps: ['A — Trachea: lined with ciliated pseudostratified columnar epithelium.',
                'Trachea: cartilage present; smooth muscles present.',
                'B — Bronchus: lined with ciliated pseudostratified columnar epithelium (1).',
                'Bronchus: smooth muscles present (2); cartilage present (3).',
                'C — Bronchiole: lined with cuboidal epithelium.',
                'Bronchiole: cartilage absent; smooth muscles present.',
                'D — Alveoli: composed of mainly type 1 pneumocytes = squamous epithelium for gaseous exchange.',
                'Alveoli: a smaller number of type 2 pneumocytes for surfactant production; macrophages to keep the alveoli clean.',
                'Alveoli: no cartilage or muscles present.',
                'The smooth muscles are relaxed by bronchodilators (the reliever); cortisol, daily (the preventer), reduces the inflammation.'] },
    ],
    formative: ['the term used to describe difficulty breathing'],
    done: 'Name dyspnoea; say what narrows the airway in an attack and what that does to resistance and ventilation; how a reliever and a preventer work; the lungs’ defences and the muco-ciliary escalator (and what smoking does to it); the baroreflex that brings blood pressure back down afterwards; and her four lung micrographs — trachea, bronchus, bronchiole, alveoli — by lining, cartilage and smooth muscle.',
    ask: 'Eight written questions from 1 to 4 marks; the baroreflex one is the longest. Her exam helpline adds “CASE STUDY LUNG HISTOLOGY FOR EXAM” under this case: expect her four micrographs, perhaps unlabelled.',
    cap: 'The asthmatic airway, the inhaler and preventer, the escalator, the full baroreflex loop, and the four airway micrographs.' },
  { id: 'c4', n: 4, from: 'm1:panic', mod: 'm1', sys: 'resp', name: 'Exam case 4 · Panic attacks',
    formative: [],
    done: 'Bullet the steps of inhalation and exhalation, name the forced-breathing muscles, list what makes ventilation easier or harder, and run the bicarbonate buffer both ways: hyperventilation → CO2 down → pH up (respiratory alkalosis), and how breathing corrects a metabolic change.',
    ask: 'Eight written questions; the buffer equation is asked outright, and the acid–base tables are written out.',
    cap: 'Ventilation mechanics, normal pH, the buffer equation and which way each change pushes it.' },

  { id: 'c6', n: 6, mod: 'm2', sys: 'endo', name: 'Exam case 6 · Diabetes',
    scenario: 'Larry has been recently diagnosed with Type 2 diabetes mellitus, an endocrine disorder, after what appears to be many years of uncontrolled hyperglycaemia. He must measure his blood sugar every as he works with his diabetes nurse to bring it under control, and he will also need to have insulin injections and other medications to help his blood glucose regulation. Larry is a little overwhelmed, and isn’t sure of what this insulin is for. As his nurse, you need a robust understanding of what insulin does in the body. Diabetes mellitus is a disease that involves the dysfunction of insulin and glucose regulation. There are two types, type 1 where the body fails to make insulin, and type 2 where the body is unable to respond to insulin when it is secreted.',
    questions: [
      { q: 'Where in the body, SPECIFICALLY, is insulin made?', marks: 2, src: DECK24 + ', slide 24',
        steps: ['The endocrine pancreas — in the islets of Langerhans.',
                'Beta cells in the islets make INSULIN, which decreases blood sugar levels (after a meal it stimulates the body to store excess glucose). Alpha cells make glucagon — both have A’s.'] },
      { q: 'What hormone (or hormones!) acts in opposition to insulin, and where is it/they made?', marks: 3, src: DECK24 + ', slide 25',
        steps: ['Glucagon — the pancreatic hormone (alpha cells) that increases blood glucose levels.',
                'Adrenaline/epinephrine (adrenal medulla) and cortisol (adrenal cortex) — both mediate the stress response (fight or flight, long-term stress), when the body needs ready access to glucose.',
                'Growth hormone (anterior pituitary) and thyroid hormones — associated with metabolism; changes in them can increase blood sugar.'] },
      { q: 'Explain what insulin does at a cellular level (you’ll need to think about how it travels in the body, what it binds to, and what happens).', marks: 4, src: DECK24 + ', slides 28–29',
        steps: ['Insulin travels through the body in the blood.',
                'It binds to insulin receptors on the surface of insulin-sensitive cells.',
                'Once bound, a cascade of events inside the cell moves the GLUT4 transporter from inside the cell into the cell membrane.',
                'In the membrane GLUT4 is a transport protein that lets glucose move into the cell, down its concentration gradient, by facilitated diffusion.'] },
      { q: 'Insulin’s role in the liver is:', marks: 1, src: DECK24 + ', slide 31',
        steps: ['To stimulate the conversion of glucose to glycogen (the storage form of glucose) via glycogenesis — enzymes join the glucose molecules together into the larger glycogen polysaccharide.'] },
      { q: 'Insulin’s role in the muscles is:', marks: 1, src: DECK24 + ', slide 31',
        steps: ['To stimulate the conversion of glucose to glycogen (the storage form of glucose) via glycogenesis.'] },
      { q: 'Insulin’s role in the fat tissue is:', marks: 1, src: DECK24 + ', slide 31',
        steps: ['To stimulate the conversion of glucose to fats (the most efficient storage form — more energy in a smaller space) via lipogenesis.'] },
    ],
    formative: ['insulin s role in the liver is to stimulate'],
    done: 'Where insulin is made (beta cells, islets of Langerhans), the hormones that oppose it and where each comes from, the GLUT4 story at the cell, and insulin’s job in liver, muscle and fat.',
    ask: 'Six short written answers (1–4 marks); her formative test asks the liver / muscle / fat roles as drop-downs.',
    cap: 'Pancreas → receptor → GLUT4 → glycogenesis / lipogenesis, and the opposing hormones.' },

  { id: 'c8', n: 8, mod: 'm2', sys: 'ms', name: 'Exam case 8 · Joints and arthritis',
    scenario: 'Shannon is a 30-year-old woman that has had a series of issues with her joints. She has had bursitis in her hip in the past, and is now has presented mainly with pain in her knee and hip joints, as well as her hands. After consultation, she has recently been diagnosed with rheumatoid arthritis. She is concerned, as she feels she is too young to have arthritis, even though she is fairly active and has been an athlete most of her life. Part of the treatment plan that manage the joint includes the use of prednisone. Prednisone is a synthetic corticosteroid, similar to cortisol. Cortisol is part of the body’s long term stress response.',
    questions: [
      { q: 'Arthritis is a condition that affects the joints of the body. What are the structures of the joint? Use the diagram and name the lettered structures, with the function of each.', marks: 9, img: 'wb26-joint.png',
        src: JOINTS + ', slide 3 — her answer letters the muscle I; this workbook figure letters it A (top left), so the answer follows the workbook',
        steps: ['A (top left) — muscle: contracts and acts on the bones, making the angle between them smaller or larger.',
                'A (top right and bottom) — enthesis: where the ligaments attach.',
                'B — synovial fluid: lubricates the joint.',
                'C — bursa: reduces friction (a lubricated, fluid-filled sac between bone and soft tissue).',
                'D — joint capsule: holds the bones together.',
                'E — tendon: joins muscle to bone.',
                'F — bone: acts as a lever and articulates at joints.',
                'G — hyaline cartilage: reduces friction and absorbs shock.',
                'H — ligament: holds bones together.'] },
      { q: 'What occurs in rheumatoid arthritis?', marks: 4, src: JOINTS + ', slide 10 (her rheumatoid vs osteoarthritis table)',
        steps: ['It is autoimmune: the immune system attacks the joints.',
                'Onset is relatively rapid, over weeks to months, and it may begin at any time in life.',
                'Joints are painful, swollen and stiff — often small and large joints on BOTH sides of the body (both hands, wrists, elbows, balls of the feet); morning stiffness lasts longer than 1 hour.',
                'Whole-body (systemic) symptoms: frequent fatigue and a general feeling of being ill.'] },
      { q: 'What is the other type of arthritis called?', marks: 1, src: JOINTS + ', slide 10',
        steps: ['Osteoarthritis.'] },
      { q: 'What is the difference between the above and rheumatoid arthritis?', marks: 4, src: JOINTS + ', slide 10',
        steps: ['Cause: rheumatoid is autoimmune; osteoarthritis is wear and tear.',
                'Onset: rheumatoid may begin any time in life and comes on over weeks to months; osteoarthritis usually begins later in life, slowly over years.',
                'Joints: rheumatoid — painful, swollen, stiff, symmetrical, small and large joints, morning stiffness over 1 hour; osteoarthritis — ache and tenderness with little or no swelling, usually one set of joints (fingers, thumbs, hips, knees, spine), morning stiffness under 1 hour.',
                'Rheumatoid has whole-body symptoms (fatigue, feeling ill); osteoarthritis does not.'] },
      { q: 'Where is cortisol produced and secreted from the body?', marks: 2, src: JOINTS + ', slides 5–6',
        steps: ['In the adrenal glands — paired, pyramid-shaped organs on top of the kidneys.',
                'In the adrenal CORTEX (the outer, glandular part): cortisol is its major glucocorticoid; its release is stimulated by ACTH from the anterior pituitary.'] },
      { q: 'What are the functions of cortisol and how is this related to the stress response?', marks: 4, src: JOINTS + ', slides 6 and 11',
        steps: ['Increases blood glucose — forms glucose from non-carbohydrate sources (gluconeogenesis) — and increases blood fatty acids and amino acids.',
                'Prepares the body to resist chronic (long-term) stress by keeping blood sugar levels relatively constant and maintaining blood volume.',
                'Maintaining blood volume maintains tissue perfusion, so oxygen and nutrients are available to deal with the stress.',
                'Reduces inflammation (less swelling, redness and pain) and suppresses the immune system.'] },
      { q: 'How is cortisol going to aid in Shannon’s rheumatoid arthritis?', marks: 2, src: JOINTS + ', slide 11',
        steps: ['It reduces inflammation: less swelling, redness and pain in her joints.',
                'It suppresses the immune system: rheumatoid arthritis is an autoimmune condition, an overactive immune system.'] },
    ],
    formative: ['the part labeled b in the diagram is known as'],
    done: 'Name and give the function of every lettered joint structure, describe rheumatoid arthritis, name osteoarthritis and set the two side by side, and explain where cortisol comes from, what it does in stress, and why it helps Shannon.',
    ask: 'A label-and-function table on her joint figure, then short written answers; her formative test asks the joint letters as drop-downs.',
    cap: 'Her nine structures, her RA-vs-OA table, and cortisol’s jobs.' },

  { id: 'c9', n: 9, mod: 'm2', sys: 'ns', name: 'Exam case 9 · Neurotransmitters and the brain',
    scenario: 'Mr Paraone has been admitted to hospital after a fall and has reported they are having issues with mobility and tremors. Mr Paraone is later diagnosed with Parkinson’s disease. This is a brain disease where cells that normally make Dopamine, a neurotransmitter, start to die. One of the treatments to help control their symptoms is called Levodopa, which travels through the blood and into the brain to help to boost the brain’s Dopamine levels, so the neurons can continue to communicate properly via their synapses.',
    questions: [
      { q: 'What is a neurotransmitter? Where is the neurotransmitter Dopamine normally made in the central nervous system?', marks: 2,
        src: 'Her words · her 2026 NS1 deck, slide 13 (chemical synapses) and her LEARNING PAGE NS2 (brain stem)',
        steps: ['A neurotransmitter is a chemical substance released at the presynaptic endings of a chemical synapse, which then acts on the receptor region of the postsynaptic neuron.',
                'Dopamine is made in the substantia nigra of the midbrain (brain stem).'] },
      { q: 'Explain the role of Calcium ions (Ca2+) in synaptic transmission.', marks: 2, src: NS24 + ', slide 4',
        steps: ['When the action potential (electrical nerve impulse) reaches the axon terminal of the presynaptic neuron, Ca2+ channels open and Ca2+ enters the presynaptic neuron.',
                'The Ca2+ helps the neurotransmitter vesicles open, releasing the neurotransmitter into the synaptic cleft by exocytosis.'] },
      { q: 'Explain the process of synaptic transmission that allows neurotransmitters to be released. Use the diagram to help you in your explanation.', marks: 6, img: 'wb26-synapse.png', src: NS24 + ', slides 3–5',
        steps: ['The action potential (electrical impulse) reaches the axon terminal of the presynaptic neuron and stimulates the entry of Ca2+ (Ca2+ channels open) into the presynaptic neuron.',
                'Ca2+ helps the neurotransmitter vesicles open, releasing the neurotransmitter into the synaptic cleft by exocytosis.',
                'The neurotransmitter diffuses across the synaptic cleft.',
                'The neurotransmitter binds to receptors on the postsynaptic neuron.',
                'The postsynaptic membrane’s permeability changes, causing either an excitatory or an inhibitory effect.',
                'Re-uptake or enzymatic destruction of the neurotransmitter.'] },
      { q: 'When neurotransmitters bind to a receptor, what happens?', marks: 2, src: NS24 + ', slides 3–4',
        steps: ['The postsynaptic membrane’s permeability changes,',
                'causing either an excitatory or an inhibitory effect — the postsynaptic neuron is stimulated or inhibited.'] },
      { q: 'After the neurotransmitter has been released, what happens to that chemical signal?', marks: 1, src: NS24 + ', slides 3–4',
        steps: ['It is removed: re-uptake into the presynaptic neuron, or enzymatic destruction of the neurotransmitter.'] },
    ],
    formative: ['b is pointing towards a vesicle containing'],
    done: 'Define a neurotransmitter, say where dopamine is made, give calcium’s role, and walk the six steps of synaptic transmission from the action potential to re-uptake.',
    ask: 'Short written answers; the six-step sequence is the long one, and her formative test asks the synapse figure as drop-downs.',
    cap: 'Her six steps in order, excitatory vs inhibitory, re-uptake or enzymes.' },

  { id: 'c10', n: 10, mod: 'm2', sys: 'ns', name: 'Exam case 10 · Stroke and the brain',
    scenario: 'You are working in a stroke rehabilitation unit, and are often interacting with individuals that are recovering from stroke, cerebrovascular accident, when parts of the brain are damaged during periods of ischaemia. Different areas of the brain control different tasks, so the symptoms a person shows, or the functions they have lost will be reflective of the part of their brain that has been damaged by the ischaemia. You are working with a range of people with differing functions, and you’re thinking about what parts of the brains must be involved.',
    questions: [
      { q: 'Review the functional regions of the cerebrum using this image: name the functional area at each letter, A to G.', marks: 7, img: 'wb26-cerebrum.png', src: NS24 + ', slide 10 (her key: 1=F, 2=B, 3=D, 4=G, 5=C, 6=E, 8=A)',
        steps: ['A — prefrontal cortex.', 'B — Broca’s area.', 'C — the (pre)motor area, precentral gyrus.', 'D — the somatosensory area, postcentral gyrus.',
                'E — the auditory area.', 'F — Wernicke’s area.', 'G — the occipital (visual) area.'] },
      { q: 'For each region, brainstorm the possible changes to function or behaviour that would result from damage to that region.', marks: 7, img: 'wb26-cerebrum.png',
        src: NS24 + ', slide 10 gives what each area DOES; each line’s “damage →” half is the tool’s reading of that function',
        steps: ['A, prefrontal cortex (problem-solving, judgement, inhibiting inappropriate behaviour, keeping the mind on goals) → poor judgement, inappropriate behaviour, loss of focus.',
                'B, Broca’s area (talking, writing, producing speech that can be understood) → difficulty producing speech and writing.',
                'C, motor area (muscle movements are “instructed” from here, each muscle group mapped) → loss of voluntary movement of the mapped parts.',
                'D, somatosensory area (every part of the body is represented; general senses such as touch arrive here) → loss of touch and other general sensation.',
                'E, auditory area (hearing, regions attuned to different frequencies) → hearing affected.',
                'F, Wernicke’s area (understanding spoken and written language) → cannot understand language.',
                'G, occipital area (the visual processing system, primary visual cortex) → vision affected.'] },
    ],
    formative: ['judgment reasoning and impulse control can be improved', 'a person who did not take any alcohol or drugs behaved like a drunk person'],
    done: 'Put a name and a function on every lettered area of her cerebrum figure, and say what damage there would change — plus the guided “where is it” answers for the cerebellum, pons, medulla and corpus callosum.',
    ask: 'Her figure with letters; her formative test asks the areas as drop-downs and the four brain-part locations as fill-in-the-gaps.',
    cap: 'Her seven lettered areas, and the four “other brain parts” locations.' },

  { id: 'c13', n: 13, mod: 'm3', sys: 'repro', name: 'Exam case 13 · Fertility',
    scenario: 'Rose and Simon are seeing the nurse at their local GP’s clinic, as they have recently made the decision to begin trying to conceive. Rose has been on the Depo Provera injection as a method of contraception for the past 2 years. As her nurse, you advise that it could take a little while for her normal cycle to settle after coming off this hormonal contraceptive. Rose takes your recommendation about tracking her cycle after learning that there are limited days in the month where she will be fertile and able to conceive. She has also taken your recommendation about purchasing an ovulation predictor kit and some pregnancy tests.',
    questions: [
      { q: 'What is an ovulation predictor kit? What does it show?', marks: 1, src: FERT + ' (her true/false statement)',
        steps: ['An ovulation predictor kit shows when ovulation is about to happen since it picks up the sharp peak in the luteinizing hormone (LH) in the urine just before ovulation.'] },
      { q: 'What occurs during ovulation?', marks: 4, src: FERT + ' (her six-blank ovulation question, blanks filled with her keys)',
        steps: ['A secondary oocyte is released from the ovary.', 'Ovulation is triggered by a peak in the levels of LH.',
                'The ovarian wall ruptures when the fluid-filled cyst, the Graafian or tertiary follicle, bursts.',
                'The oocyte must be pushed by the force of fluid out of the ovary and toward the fimbriae of the Fallopian tube.'] },
      { q: 'What days of a female’s cycle are they fertile? Use the accompanying image to answer.', marks: 1, img: 'wb26-cycle.png', src: FERT,
        steps: ['Days 10–17.'] },
      { q: 'Can you explain why the hormone levels change over the course of the menstrual cycle?', marks: 2, src: FERT + ' (her true/false statement)',
        steps: ['Hormone levels change over the course of the menstrual cycle since each hormone is driving a different process.',
                'We need follicles to develop (FSH), uterine lining to thicken (estrogen), ovulation (LH), and the uterus to prepare for implantation and pregnancy (progesterone).'] },
      { q: 'How would pregnancy change the hormone levels graph?', marks: 2, src: FERT + ' (her two keyed statements)',
        steps: ['The hormone drop that we see at roughly day 21 would not occur in successful implantation and pregnancy.', 'The estrogen and progesterone levels will keep rising.'] },
      { q: 'Hormonal methods of contraception tend to impact a female’s fertility by using progesterone. Describe how we use the normal functions of the hormone progesterone to prevent pregnancy?', marks: 3,
        src: S24 + ', 27:28 — her spoken answer to her mini-pill question (what it does, before the oxytocin distractor it does not)',
        steps: ['It prevents ovulation: it prevents the LH from being released.',
                'It thickens the cervical mucus, so it keeps the sperm out.',
                'It imitates pregnancy by keeping the progesterone levels high.'] },
    ],
    held: [
      { q: 'Male and female fertility are different – what are some of the key factors in male and female fertility?', why: 'her Fertility quiz does not cover it, no answer of hers is posted, and her 2024 case session does not answer it' },
      { q: 'Contraception can be hormonal or non-hormonal. Summarise the differences in a tabular form.', why: 'her Fertility quiz and her 2024 session cover only four methods (condom = barrier, IUD = stops implantation, hormonal = stops ovulation, abortion) — see the quiz’s matching question' },
      { q: 'What are the functions of the sex hormones in the human body?', why: 'no answer of hers posted; her 2024 session covers only their jobs in the cycle (FSH grows follicles, LH triggers ovulation, estrogen and progesterone ready the lining)' },
      { q: 'Injections with the hormone FSH usually form part of In Vitro Fertilization (IVF) protocols. What is IVF, when would this procedure be appropriate and what would be the purpose of the FSH injections?', why: 'no answer of hers posted; her 2024 session says only that FSH is “for the growth of the follicles”' },
    ],
    pull: ['m3:211050'],
    formative: [],
    done: 'Explain the ovulation predictor kit (the LH surge), what happens at ovulation step by step, the fertile days on her graph, why the hormones rise and fall, and what pregnancy does to the graph — then the contraception and sex-hormone questions she has not answered yet.',
    ask: 'Her Fertility quiz turns this case into matching, true/false, a six-blank drop-down and MCQs; the exam may ask any of them written. Her 2024 session (17:28–24:13, 37:21): the cycle graph IS in the exam, but the labels may be taken away (phase, hormone and cycle names, letters instead) — know each curve by its shape: LH peaks just before ovulation, progesterone is low then peaks in the second half, and FSH goes with follicular and proliferative (“keep the F’s together”).',
    cap: 'The cycle graph, the LH surge, ovulation in order, and why the late-cycle drop does not happen in pregnancy.' },

  { id: 'c14', n: 14, mod: 'm3', sys: 'gen', name: 'Exam case 14 · RG colour blindness',
    scenario: 'Simon is colour blind, a condition which affects his ability to distinguish between colours, with the most impact on red and green. He has expressed an interest in understanding why he has the disease, but neither of his parents do. He’s also heard that it is more common in males and so is wondering if he will pass this disease onto any sons he might have.',
    /* Her answers: her RG colour-blindness quiz (still hidden on Canvas as 211016) as she talks it through and keys it 10/10
       in her 2024 session — the same scenario and the same seven relatives as this workbook — plus her 2026 “better answer”. */
    questions: [
      { q: 'What is red-green colour blindness? (Distinguish between cones and rods, specifically where they are found in the eye; distinguish their functions using photopic, scotopic, colour, central and peripheral vision; define RG colour blindness in terms of the “inability to observe certain light frequencies”.)', marks: 7, img: 'wb26-retina.png',
        src: S24 + ', 56:02–1:00:49: her words, and her quiz keys “cones” and “L and M cones” on her graded page. The LAST line is the tool’s: it puts her “good light / dim light” into the question’s words photopic / scotopic, and gives the rods peripheral vision (the textbook term; she does not say it)',
        steps: ['Cones are for colour vision: central colour vision in good light, and much more detailed.',
                'Rods are for non-colour vision (black, white and grey scale) and more sensitive to light, so they work even in dim light.',
                'The macula has both cones and rods; the fovea has only cones.',
                'Red-green colour blindness is a genetic defect (an anomaly, not a disease) that causes dysfunction of the cones of the retina.',
                'It affects the L cones (long wavelength, red light) and the M cones (medium wavelength, green light), so red and green are hard to distinguish.',
                'It can be detected with a colour-blindness test.',
                'In the question’s words: cones = photopic (bright light), colour and central vision; rods = scotopic (dim light) and peripheral vision.'] },
      { q: 'Draw a pedigree chart to show Simon, his mum, his dad, his maternal grandmother (not colour-blind), maternal grandfather (colour-blind), maternal aunt (colour-blind) and maternal uncle (not colour-blind). Can you track how Simon inherited the disease when neither of his parents are colour blind?', marks: 7,
        src: S24 + ', 1:01:50–1:05:25: her genotype for each relative, keyed “Correct!” on her graded quiz; the uncle’s line applies her rule for Simon’s dad (not colour-blind, so the normal X), and Simon’s line her “he gives his sons only Y’s”. She says the exam will not ask you to draw the chart, only to fill genotypes in (1:00:49)',
        steps: ['Maternal grandfather: XbY — a man (Y chromosome), colour-blind, and the condition is recessive.',
                'Maternal grandmother: XBXb, a carrier — not colour-blind, but she has a colour-blind daughter.',
                'Maternal aunt: XbXb — a colour-blind woman has the defect on both her X chromosomes.',
                'Simon’s mum: XBXb, a carrier — she carried it over to Simon, but her normal XB gives her normal vision.',
                'Simon’s dad: XBY — he is not colour-blind, so he has the normal X.',
                'Maternal uncle: XBY — not colour-blind.',
                'Simon: XbY — his Xb came from his mum; his dad gave him only a Y.'] },
      { q: 'Given the above and your own research, how is red-green colour blindness inherited?', marks: 6,
        src: 'Her answer · her “What do we need to study for the exam?” post (413286, 4 Oct 2026), her “better answer” for the cause of RG colour blindness, split into lines; the first line’s genes and the last line are from her 2024 case-study session (59:09, 1:08:40)',
        steps: ['X-linked recessive: only the L (red) and M (green) cone genes are on the X chromosome.',
                'Often carried by mothers, and expressed in 50% of their sons.',
                'It only shows when all X chromosomes are affected: a woman needs both.',
                'Fathers never pass it to their sons: they give their sons only a Y.',
                'Fathers always pass the affected X chromosome to all their daughters.',
                'It can skip a generation.'] },
      { q: 'Will Simon pass on red-green colour blindness to his children? How?', marks: 2,
        src: S24 + ', 1:06:22–1:06:54: her key “To none of his sons, but to all his daughters who will be unaffected carriers”, correct on her graded quiz',
        steps: ['To none of his sons: he gives his sons only his Y.',
                'To all his daughters, who will be unaffected carriers: each daughter gets his X.'] },
    ],
    pull: ['m3:gen-sexlinked', 'm3:eye-retina'],
    formative: [],
    done: 'Rods vs cones (where, what for), RG colour blindness as faulty L and M cones, every relative’s genotype through Simon’s maternal grandfather and carrier mum, the X-linked recessive rules, and why he passes it to none of his sons but all his daughters.',
    ask: 'Her exam revision deck asks it as MCQ (“X-linked recessive”) and fill-the-gaps (retina → photoreceptor → cone). Her 2024 session: the exam will NOT ask you to draw the pedigree, but may give the phenotypes and ask for each genotype as a fill-in (1:00:49).',
    cap: 'X-linked recessive, carrier mothers, the L and M cones, and each relative’s genotype.' },

  { id: 'c15', n: 15, mod: 'm3', sys: 'gen', name: 'Exam case 15 · Genetic diseases',
    scenario: 'You’ve been working in a GP clinic, working alongside many different families, serving a rural community. Recently, you’ve been working alongside two families that have genetic diseases. One family has cystic fibrosis (the Harris whanau), and one has Huntington’s disease (the Anderson whanau). You are wanting to understand more about how these diseases are passed from person to person, and how this might affect any future children that are born into these families.',
    questions: [
      { q: 'What are the modes of inheritance of Huntington’s disease and Cystic Fibrosis? Explain the modes of inheritance for both diseases (chromosome type, pattern of inheritance, what this means).', marks: 6,
        src: S24 + ', 1:16:17 and 1:30:03–1:31:53: she names cystic fibrosis autosomal recessive and Huntington’s autosomal dominant, then marks a student’s board answer to this question “all of that is right”, adding in red that the answer must name the AFFECTED person (CF rr; Huntington’s Rr or RR). The chromosome numbers are that student’s, read off her screen; its “RR – heterozygous” slip is left out (RR is homozygous)',
        steps: ['Cystic fibrosis: autosomal recessive, on chromosome 7.',
                'It skips generations; people can be carriers.',
                'The affected person is rr (homozygous).',
                'Huntington’s disease: autosomal dominant, on chromosome 4.',
                'It is expressed whenever the dominant allele is present: in every generation someone is expected to have it.',
                'The affected person is Rr or RR.'] },
    ],
    held: [
      { q: 'For the pedigree chart of the Harris whanau, state the genotype and phenotype of every person.', why: 'needs her pedigree figure and her model answer (board 413346, hidden); her 2024 session does not work it' },
      { q: 'There are two sisters that are the youngest members of this whanau. What is the chance that they could pass this genetic condition onto their children? What circumstances would have to occur?', why: 'her model answer is on board 413346, hidden on Canvas as of 5 Oct; her 2024 session does not work it' },
      { q: 'For the pedigree chart of the Anderson whanau, state the genotype and phenotype of every person.', why: 'needs her pedigree figure and her model answer (board 413346, hidden); her 2024 session shows the chart but does not work it' },
      { q: 'There are 6 cousins that are the youngest generation of this whanau (numbers 1–6 of the third generation). What is the chance that they could pass this genetic condition onto their children?', why: 'her model answer is on board 413346, hidden on Canvas as of 5 Oct; her 2024 session does not work it' },
    ],
    pull: ['m3:gen-disorders', 'm3:gen-pedigree'],
    formative: [],
    done: 'Cystic fibrosis = autosomal recessive (carriers, skips generations); Huntington’s = autosomal dominant on chromosome 4 (one copy is enough). Read both family pedigrees for every genotype and phenotype, and work out the chance each youngest member passes it on.',
    ask: 'Pedigree charts with written genotypes, and a mode-of-inheritance table; her Module 3 help board names Huntington’s in these words.',
    cap: 'Recessive vs dominant autosomal patterns, reading a pedigree, one Punnett square per couple.' },
];
