/* helpline-m1.js — HER worked answers from the MODULE 1 HELPLINE board (discussion 413337), from his save of 21 Sep 2026
   (_inbox/HS2 Module 1 Capture/HS2BOARD-module-1-helpline.htm — the harvest had kept only its title).
   Verbatim; the only edits are mechanical: her four-column ventilation table is set out one breath at a time (row labels
   kept), her " / " line breaks are new lines. Keyed by the Module 1 checklist row it answers (the four criteria she quotes
   in the post). `pin` = the questions each section is shown under, read one by one on 21 Sep 2026: a question it does not
   answer (pneumothorax, gas laws, the bell jar, cardiac output x resistance, erection) is left off. `stems` = fragments of
   the final's own case / revision-deck questions it also answers (matched in build.mjs; a fragment that matches nothing
   fails the build). */
const URL = 'https://canvas.manukau.ac.nz/courses/61986/discussion_topics/413337';
const FROM = 'MODULE 1 HELPLINE';

export const HELPLINE_M1 = {
 'cvs-bp-control': { url: URL, from: FROM, hl: 'Blood pressure control (her checklist item 12)',
  parts: [
   { h: 'HOW SHE SAYS IT CAN BE ASKED — SHORT TERM NEURAL MECHANISMS / BARORECEPTOR REFLEX',
     t: 'Explain the short-term neural/baroreceptor reflex.\nand anything related to where the baroreceptors are found/how they work/where they send their impulses to.\nReflexes consist of a receptor, an integrative centre and an effector. Use this framework to analyse the reflex action involved in the baroreceptor response to low/high blood pressure (see image).\nExplain the role of brain parts /the medulla oblongata/vasomotor centre /cardioacceleratory /cardioinhibitory centres in the control of blood pressure.\nDiscuss the role of the baroreceptor reflex in the control of peripheral resistance.\nWhat effect would adrenaline have on blood pressure and how does it work?\nExplain how Calcium channel blockers can help in lowering blood pressure.' },
   { h: 'THE RAAS SYSTEM',
     t: 'Explain the indirect renal control of of blood pressure /RAAS system .\nDiscuss the role of enzymes in the RAAS system (Renin (from granular cells in kidney) and ACE (from lungs) are both enzymes).\nIdentify the hormones involved in the RAAS system and explain the role of each (Angiotensinogen (hormone precursor) , Angiotensin II, Aldosterone from adrenal glands, ADH from posterior pituitary)\nDifferent organs ( liver (angiotensinogen), lungs (ACE), kidneys (Renin), pituitary (ADH), adrenal glands (aldosterone)) secrete substances into the bloodstream to take part in the RAAS mechanism. Discuss this statement.\n5. Discuss the role of the indirect renal mechanism in the control of stroke volume.\n6. Explain the effects of Angiotensin 2 on blood pressure .\n7. Explain why antihypertensive medication (like ACE inhibitors) aims at preventing the formation of Angiotensin 2 specifically .' },
   { h: 'KIDNEY',
     t: 'Explain the direct renal control of blood pressure. Anything like how the direct renal mechanism modifies SV and how that impacts blood pressure.\nDiscuss the role of the kidney in the control of stroke volume (this would entail both direct and indirect renal mechanisms (hint: it is about the volume of blood).\nExplain how antidiureticums can help in lowering blood pressure.\nThe effect of changing blood pressure and afferent arteriole diameter on Renal Blood Flow (RBF), Pressure in the glomerulus (P G ), and Glomerular Filtration Rate (GFR) and resulting urine output.' },
   { h: 'DIRECT RENAL MECHANISM — her worked answer',
     t: 'LOW BLOOD PRESSURE: Decrease in blood pressure --> Decrease in blood flow in afferent arteriole --> Decrease in blood flow in glomerulus (GFR)--> Decrease of filtrate in capsule of Bowman--> Decrease of urine output--> Less fluid lost--> Fluid volume in body increases ==> BP Increases\nHIGH BLOOD PRESSURE: Increase in blood pressure-->Increase in blood flow in afferent arteriole --> Increase in blood flow in glomerulus (GFR)--> Increase of filtrate in capsule of Bowman--> Increase of urine output--> More fluid lost--> Fluid volume in body decreases ==> BP Decreases\nIf you truly understand the concept of blood pressure control, none of these should be difficult.\nIf you learn any of the concepts like a parrot without understanding, you will struggle.' },
   { h: 'A STUDENT ASKED: only baroreceptors, not chemoreceptors?',
     t: 'Answer: For neural blood pressure regulation, we just focus on the story involving the baroreceptors.\nFor breathing regulation, we just focus on the story involving the chemo receptors.\nAnswer : This assumption is not true, but we are not focusing on chemoreceptors and blood pressure. Chemoreceptors are stimulated by hypoxia/hypercapnia to raise Blood Pressure as a back-up mechanism.' },
  ],
  pin: ['qee1ee274dc', 'qce795b1c3c', 'q6994c1e695', 'q1b2feb36dd', 'q90c609b64f', 'q441c19cb56', 'qc7e3923d97', 'q8f8aa2ef09', 'q5e2fe89d7f', 'q25650249d5',
        'qf118c30eb4', 'q748a1d0d4c', 'q9a9c2b34f0', 'qac09650676', 'q02437916dd', 'qde24b8f42e', 'q9f07d54541', 'qa122a19587', 'qe534856e4d'],
  stems: [['case-c3', 'blood pressure was high due to their fight or flight response'], ['rev-exam', 'what parts of the brain help to return blood pressure to normal'],
          ['rev-exam', 'decreasing blood pressure requires'], ['rev-exam', 'barorecptors of the body are located in']] },

 'resp-ventilation': { url: URL, from: FROM, hl: 'Pulmonary ventilation (her checklist item 7)',
  parts: [
   { h: 'PROCESS OF PULMONARY VENTILATION — her table (“Any of the following could be a short SAQ”)',
     t: 'QUIET INHALATION — Active/Passive: Active process. Muscles involved: Primary breathing muscles (diaphragm & external intercostal muscles) contract. Effects of muscle movement: Diaphragm goes down (thoracic floor drops) and external intercostals lift the ribs up and out- thoracic volume enlarges. Mechanism / Volume changes: Parietal pleura clings to inner surface of thorax. Because of negative pressure in the interpleural space, the visceral pleura clings to the parietal pleura and moves with it. This stretches the lung tissue. Pressure changes: As volume increases, pressure in the lung (alveolar pressure) drops (Boyle\'s Law). Atmospheric pressure is now higher than the pressure in the lungs and air flows in from outside. Nervous control: Quiet inhalation is controlled by the VRG in the MO through the phrenic and intercostal nerves. To prevent over-stretching of the alveoli, inhalation is stopped by impulses from the Pneumotaxic Center in the PRG in the pons. Chemoreceptor input (e.g. acidity, high CO2 levels and low O2 levels) is integrated by the DRG and impulses to the VRG may alter breathing rate and depth. Alcohol and morphine overdoses may suppress the VRG totally.\n' +
        'QUIET EXHALATION — Active/Passive: Passive process. Muscles involved: diaphragm & external intercostal muscles relax. Effects of muscle movement: Thoracic volume reduced. Mechanism / Volume changes: As elastic recoil makes the lungs shrink (volume reduces). Pressure changes: As volume decreases, the pressure increases causing an outwards pressure gradient, air flows out. Nervous control: Marieb, et al., (11 ed) (2019) state that when the VRG\'s expiratory neurons fire, the output sops, and expiration occurs as the inspiratory muscles relax and the lungs recoil.\n' +
        'FORCED INHALATION — Active/Passive: Active process. Muscles involved: Primary breathing muscles (diaphragm & external intercostal muscles) contract and the thoracic volume is further enlarged by the contraction of the accessory breathing muscles namely the sternocleidomastoid, the scalenes, the serratus and pectoralis muscles. Effects of muscle movement: thoracic volume enlarges even more. Pressure changes: Intrapleural (alveolar pressure decreases even more than with only primary muscle contracting. Pressure gradient increases.\n' +
        'FORCED EXHALATION — Active/Passive: Active process. Muscles involved: Primary breathing muscles (diaphragm & external intercostal muscles) relax. The abdominal muscles contract to push the abdominal contents up against the diaphragm to further reduce the size of the thoracic cavity. Effects of muscle movement: Thoracic volume reduced even more. Pressure changes: Intrapleural (alveolar pressure increases even more than with only primary muscle relaxing. Pressure gradient increases. Nervous control: Older sources (on which the original HS2 Powerpoints were based) say the DRG is active- more recent sources do not mention the DRG as active. Marieb, et al., (11 ed) (2019) state that forced expiration and passive expiration may involve separate groups of neurons.' },
   { h: 'FACTORS THAT AFFECT PULMONARY VENTILATION',
     t: 'airway resistance - high resistance makes ventilation harder as the air flows with more difficulty through narrowed ducts.\nsurface tension - high surface tension makes the walls of the alveoli stick together and makes ventilation harder. Surfactant, made by the pneumocytes type 2 in the alveoli as well as the cuboidal epithelium in the bronchiole, helps to reduce surface tension to make ventilation easier.\nlung compliance: high compliance (as seen in conditions such as emphysema) makes the alveoli floppy - they lose their elasticity and elastic recoil, trapping air in the alveoli. Low compliance (as seen in conditions such as sclerosis due to scarring (e.g. in conditions such as cystic fibrosis, asbestosis) makes the lungs rigid and stiff. The alveoli resists movement, making ventilation difficult.\nnegative intrapleural pressure: intrapleural pressure is the pressure between the visceral and parietal pleural layers and should be negative so that lungs can adhere to the chest wall- when chest cavity enlarges, it makes the lungs to become stretched so that as the volume enlarges, the pressure decreases and air flows in.' },
   { h: 'A STUDENT ASKED: which muscles would not contract for a deep breath and a cough?',
     t: 'As we discussed on Facebook, all these muscles are involved in deep inhalation (serratius, diaphragm and external intercostals) and coughing (=forced exhalation) (rectus abdominis).\nHowever,the diaphragm and external intercostal are the primary muscles of inhalation - definitely involved. Serratius may be contracting, depending on the way and depth of inhaling.' },
  ],
  pin: ['qb949a00fe4', 'q535170b50f', 'q8d2434450a', 'q67f10cb5df', 'qd3bf05c8e4', 'qed987e85aa', 'q240e98cd35', 'qcd6cc3477a', 'qd281112b71', 'q4be7d1967b'],
  stems: [['case-c4', 'bullet point the steps involved in manaia s inhalation'], ['case-c4', 'bullet point the steps involved in manaia s exhalation'],
          ['case-c4', 'which muscles are used in forced breathing'], ['case-c4', 'factors that influence your pulmonary ventilation'],
          ['rev-exam', 'in bronchodilation airway resistance']] },

 'resp-co2-transport': { url: URL, from: FROM, hl: 'Carbon dioxide transport (her checklist item 12)',
  parts: [
   { h: 'CARBON DIOXIDE IS CARRIED IN THREE WAYS IN THE BLOOD',
     t: '70%: carried as bicarbonate : Carbonic anhydrase is an enzyme in the red blood cells that is involved in the conversion of carbon dioxide to carbonic acid and finally to bicarbonate in the red blood cell. (catalyses the underlined reaction reversibly). CO2 + H2O <-->H2CO3 <--> HCO3- + H+ (In the tissues the reaction goes to the right (in uploading CO2 to the blood) and in the lungs it goes to the left so that CO2 can be offloaded from the blood to be exhaled).\n7-10%: CO2 is more soluble in water than oxygen. Carbon dioxide carried in dissolved form in the plasma.\nAround 20% of the CO2 binds with the amino groups of hemoglobin to form carbaminohemoglobin.' },
  ],
  pin: ['q71dce49f5c', 'q850dd958b9'],
  stems: [['case-c4', 'draw the chemical equation'], ['rev-exam', 'h2co3 is what molecule'], ['rev-exam', 'hco3 is what molecule'], ['rev-exam', 'co2 is what molecule in the bicarbonate buffer system']] },

 'lymph-anatomy': { url: URL, from: FROM, hl: 'Functional anatomy of the lymphatic system (her checklist item 2)',
  parts: [
   { h: 'WHAT SHE SAYS “FUNCTIONAL ANATOMY” INCLUDES — a pointer, not an answer',
     t: 'Functional anatomy includes e.g. what is going on in the lymph nodes (cells, structure and functions), what keeps lymph flowing, what prevents backflow, how do the lymph capillaries get the fluid from the interstitial spaces, what are the main functions of the spleen and the thymus, etc.' },
  ],
  pin: [], stems: [] },
};
