/* HER EXAM REVISION DECK — "Exam Revison ppt for Hs2 Final.pptx", linked from her Module 3 Completion page ("Download Exam
   Revision ppt for Hs2 Final"). Slides 2–24 are a charades game (her key terms, one per slide); slides 25–84 are 30 questions,
   each followed by its ANSWER slide. Her answers are shown in RED on the answer slide — the correct option of an MCQ, the
   filled blanks, the T/F letters — so every key below was read off the rendered answer slide (21 Sep 2026), not guessed.
   Stems and options are hers, word for word (her spelling kept: "synpatic", "Reccessive", "Barorecptors").
   `q` = question slide, `a` = answer slide. `fig:1` shows the question slide as the question's figure (her brain letters,
   pedigrees, cycle graph, bronchioles, and her fill-the-gap scaffolds). Every question carries its answer slide as "her
   slide" under it, opened only once marked (or by a peek in Learn mode). Written answers are her red text, one line a mark.
   Two liberties, both said here: her T/F slide (73) is four statements under one heading, dealt as four T/F questions; and on
   her insulin answer (50) the blank in "promotes glucose ____ by" is left empty — "storage" is from her own next line ("glucose is stored"). */
export const REVDECK = {
  slug: 'Exam-Revison-ppt-for-Hs2-Final', quiz: 'rev-exam', name: 'Her exam revision deck (for the final)',
  charades: ['prefrontal cortex', 'exocytosis', 'glycogenesis', 'dominant', 'baroreceptor', 'airway resistance', 'lymphoedema', 'carrier', 'fertile', 'cervix', 'colour blind'],
  items: [
    { q: 25, a: 26, mod: 'm1', sys: 'resp', type: 'essay', fig: 1, stem: 'Which image would represent an asthmatic bronchiole and why?',
      steps: ['The right-hand one: it is bronchoconstricted.', 'Thicker wall — swelling.', 'More mucus — taking up the space in the lumen.', 'Together, this makes this one have a higher resistance.'] },
    { q: 27, a: 28, mod: 'm1', sys: 'lymph', type: 'mcq', stem: 'How are the lymphatics related to oedema?',
      opts: ['Increases Hydrostatic Pressure', 'Increases Osmotic Pressure', 'Decreases capillary permeability', 'Prevents drainage of the interstition'], key: ['Prevents drainage of the interstition'] },
    { q: 29, a: 30, mod: 'm2', sys: 'ns', type: 'mcq', fig: 1, stem: 'The area labelled B’s function is to',
      opts: ['Receive visual information from the retina of the eyes', 'Receive auditory information from the cochlea in the inner ear', 'Make sense of verbal language as it is heard (turns sound into speech)', 'Coordinate the movement of the mouth for speech'], key: ['Coordinate the movement of the mouth for speech'] },
    { q: 31, a: 32, mod: 'm2', sys: 'ns', type: 'essay', fig: 1, stem: 'Explain the process of synaptic transmission.',
      steps: ['Nerve impulses (action potentials) reach the axonal terminal of the presynaptic neuron.', 'The impulse stimulates the entry of Ca2+ (open Ca2+ channels) into the presynaptic neuron.', 'Neurotransmitter is released into the synaptic cleft by exocytosis.', 'Neurotransmitter crosses the synaptic cleft and binds to receptors on the postsynaptic neuron.', 'The postsynaptic membrane reacts, either causing a new impulse (excitatory) or stopping new impulses (inhibitory).'] },
    { q: 33, a: 34, mod: 'm2', sys: 'ns', type: 'mcq', stem: 'What ion enters the cell at the beginning of synpatic transmission?',
      opts: ['Magnesium', 'Calcium', 'Sodium', 'Potassium'], key: ['Calcium'] },
    { q: 35, a: 36, mod: 'm2', sys: 'endo', type: 'mcq', stem: 'The process of creating the glucose storage molecule is called',
      opts: ['Gluconeogenesis', 'Exocytosis', 'Glycogenesis', 'Glycogenolysis'], key: ['Glycogenesis'] },
    { q: 37, a: 38, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'In Bronchodilation, airway resistance ______ and ventilation ______',
      opts: ['Increases, increases', 'Increases, decreases', 'Decreases, decreases', 'Decreases, increases'], key: ['Decreases, increases'] },
    { q: 39, a: 40, mod: 'm2', sys: 'ns', type: 'mcq', fig: 1, stem: 'The area labelled C is called the',
      opts: ['Visual cortex', 'Gustatory cortex', 'Motor cortex', 'Postcentral gyrus'], key: ['Motor cortex'] },
    { q: 41, a: 42, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'In an asthma attack, what change to the airway do we want to occur?',
      opts: ['Vasoconstriction', 'Vasodilation', 'Bronchoconstriction', 'Bronchodilation'], key: ['Bronchodilation'] },
    { q: 43, a: 44, mod: 'm2', sys: 'endo', type: 'mcq', stem: 'Beta cells make ______, and alpha cells make ______',
      opts: ['Glucagon, Insulin', 'Glucagon,Glycogen', 'Insulin, Glucagon', 'Glycogen, Insulin'], key: ['Insulin, Glucagon'] },
    { q: 45, a: 46, mod: 'm2', sys: 'ns', type: 'mcq', stem: 'Personality, behaviour and abstract complex thought is thought to be control by which part of the brain?',
      opts: ['The Primary Somatosensory Cortex', 'Wernickes Area and Broca’s area', 'The Precentral Gyrus', 'The Prefrontal Cortex'], key: ['The Prefrontal Cortex'] },
    { q: 47, a: 48, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'H2CO3 is what molecule in the bicarbonate buffer system?',
      opts: ['Carbonic Acid', 'Carbon Dioxide', 'Carbon Monoxide', 'Bicarbonate'], key: ['Carbonic Acid'] },
    { q: 49, a: 50, mod: 'm2', sys: 'endo', type: 'essay', fig: 1, stem: 'Explain how Insulin impacts upon blood glucose levels (4 marks)',
      steps: ['Insulin is released from the Beta cells of the pancreas in response to high blood glucose levels.', 'Insulin helps to reduce BGL by facilitating the insertion of GLUT4 transporters into the cell membrane so glucose can enter the cell.', 'Insulin also promotes glucose storage: it acts on the muscle and liver to promote glycogenesis (glucose into glycogen), and on fat to promote lipogenesis (sugars into fats).', 'These result in decreased glucose in the blood, and glucose is stored — this decreases blood glucose back to normal.'] },
    { q: 51, a: 52, mod: 'm2', sys: 'ns', type: 'mcq', fig: 1, stem: 'The area labelled G is called the',
      opts: ['Visual cortex', 'Gustatory cortex', 'Prefrontal cortex', 'Postcentral gyrus'], key: ['Visual cortex'] },
    { q: 53, a: 54, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'Hyperventilation has what effect on CO2 in the blood and pH?',
      opts: ['Decreases CO2, increases pH', 'Decreases CO2, decreases pH', 'Increases CO2, decreases pH', 'Increases CO2, increases pH'], key: ['Decreases CO2, increases pH'] },
    { q: 55, a: 56, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'Hypoventilation has what effect on CO2 in the blood and pH?',
      opts: ['Decreases CO2, increases pH', 'Decreases CO2, decreases pH', 'Increases CO2, increases pH', 'Increases CO2, decreases pH'], key: ['Increases CO2, decreases pH'] },
    { q: 57, a: 58, mod: 'm1', sys: 'cvs', type: 'multi', stem: 'What parts of the brain help to return blood pressure to normal?',
      opts: ['Vasomotor Centre', 'Juxtaglomerula Apparatus', 'Pons', 'Cardioacceleratory Centre', 'Primary Motor Cortex', 'Cardioinhibitory centre'], key: ['Vasomotor Centre', 'Cardioacceleratory Centre', 'Cardioinhibitory centre'] },
    { q: 59, a: 60, mod: 'm3', sys: 'gen', type: 'essay', fig: 1, stem: 'Mode of inheritance? How do you know? Which coloured shape is the bb?',
      steps: ['Dominant.', 'How you know: no evidence of skips.', 'The white ones are bb.'] },
    { q: 61, a: 62, mod: 'm1', sys: 'cvs', type: 'essay', fig: 1, stem: 'Fill in the blanks: decreasing blood pressure requires ____ to HR, ____ to myocontractility, ____ to SV, ____ of arteries, ____ of artery lumen.',
      steps: ['Decreases to HR.', 'Decreases to myocontractility.', 'Decreases to SV.', 'Vasodilation of arteries.', 'Increased diameter of artery lumen.'] },
    { q: 63, a: 64, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'HCO3- is what molecule in the bicarbonate buffer system?',
      opts: ['Carbonic Acid', 'Carbon Dioxide', 'Carbon Monoxide', 'Bicarbonate'], key: ['Bicarbonate'] },
    { q: 65, a: 66, mod: 'm2', sys: 'ns', type: 'mcq', fig: 1, stem: 'The area labelled F function is to',
      opts: ['Receive visual information from the retina of the eyes', 'Receive auditory information from the cochlea in the inner ear', 'Make sense of verbal language as it is heard (turns sound into speech)', 'Coordinate the movement of the mouth for speech'], key: ['Make sense of verbal language as it is heard (turns sound into speech)'] },
    { q: 67, a: 68, mod: 'm3', sys: 'repro', type: 'mcq', fig: 1, stem: 'What is the PURPLE line?',
      opts: ['LH', 'FSH', 'Oestrogen', 'Progesterone'], key: ['Progesterone'] },
    { q: 69, a: 70, mod: 'm1', sys: 'cvs', type: 'essay', fig: 1, stem: 'Fill in the blanks: Barorecptors of the body are located in the ____, ____ and ____. The two that signal the brain for short term regulation are?',
      steps: ['The aortic arch.', 'The carotid sinus.', 'The juxtaglomerula apparatus.', 'The two for short-term regulation: the aortic arch and the carotid sinus.'] },
    { q: 71, a: 72, mod: 'm1', sys: 'resp', type: 'mcq', stem: 'CO2 is what molecule in the bicarbonate buffer system?',
      opts: ['Carbonic Acid', 'Carbon Dioxide', 'Carbon Monoxide', 'Bicarbonate'], key: ['Carbon Dioxide'] },
    { q: 73, a: 74, mod: 'm3', sys: 'gen', type: 'tf', stem: 'Autosomal Reccessive diseases… can have carriers.', key: ['True'] },
    { q: 73, a: 74, mod: 'm3', sys: 'gen', type: 'tf', stem: 'Autosomal Reccessive diseases… never skip generations.', key: ['False'] },
    { q: 73, a: 74, mod: 'm3', sys: 'gen', type: 'tf', stem: 'Autosomal Reccessive diseases… are found on the X chromosome.', key: ['False'] },
    { q: 73, a: 74, mod: 'm3', sys: 'gen', type: 'tf', stem: 'Autosomal Reccessive diseases… are found in females more.', key: ['False'] },
    { q: 75, a: 76, mod: 'm3', sys: 'gen', type: 'mcq', stem: 'RG Colourblindness is an...',
      opts: ['Autosomal Dominant condition', 'X linked dominant condition', 'Autosomal recessive condition', 'X linked recessive condition'], key: ['X linked recessive condition'] },
    { q: 77, a: 78, mod: 'm3', sys: 'senses', type: 'essay', fig: 1, stem: 'Fill in the blanks about RG colourblindness: the layer of the eye impacted is ____; the type of receptor impacted is the ____; the specific name of that receptor is a ____.',
      steps: ['The retina.', 'Photoreceptor.', 'Cone — the red and green ones.'] },
    { q: 79, a: 80, mod: 'm3', sys: 'gen', type: 'essay', fig: 1, stem: 'Mode of inheritance? How do you know? Which coloured shape is the bb?',
      steps: ['Autosomal recessive.', 'How you know: it skips a generation — two parents without the disease have a child that does.', 'The black / filled-in ones are bb.'] },
    { q: 81, a: 82, mod: 'm3', sys: 'repro', type: 'mcq', fig: 1, stem: 'What is the PINK line?',
      opts: ['LH', 'FSH', 'Oestrogen', 'Progesterone'], key: ['LH'] },
    { q: 83, a: 84, mod: 'm2', sys: 'ns', type: 'mcq', stem: 'The Parasympathetic Nerve of the Thorax is the....',
      opts: ['Oculomotor Nerve', 'Spinal Nerve', 'Vagus Nerve', 'Phrenic Nerve'], key: ['Vagus Nerve'] },
  ],
};
